# Use 4 spaces instead of tab, if you got error.
# Menus
menu:
    home: /
    archives: /archives/
    tags: /tags/
    categories: /categories/
    about: /about/

# Customize
customize:
    logo:
        width: 180
        height: 80
        url: images/logo-header.png
    theme_color: '#6cc'
    highlight: tomorrow
    sidebar: left # sidebar position, options: left, right
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon:  css/images/favicon.jpg # path to favicon
    social_links: # for more icons, please see http://fontawesome.io/icons/#brand
        github: https://github.com/charrid
        wechat: /
        weibo: /
        qq: /

# Widgets
widgets:
    - recent_posts
    - archive
    - category
    - tag
    - tagcloud
    - links

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
# 这个配置基本上用不到了，在内部代码中硬编码加了livere的评论
comment:
    disqus: hexo-theme-hueman # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here

# Share
share: bdshare # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: true # options: true, false
    google_analytics: # enter the tracking ID for your Google Analytics
    baidu_analytics: # enter Baidu Analytics hash key

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        GitHub: http://github.com/charrid